---
- name: Install requirements
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  become: yes
  with_items:
  - midori
  - matchbox
  - xinit
  - xserver-xorg
  - x11-xserver-utils

- name: Create user openslides_projector
  become: yes
  user:
    name: openslides_projector
    groups: video
    shell: /bin/bash
    state: present

- name: Create .xinitrc
  become: yes
  become_user: openslides_projector
  copy:
    dest: ~/.xinitrc
    content: |
      midori  -e Fullscreen -a http://localhost/projector/1 &
      exec matchbox-window-manager -use_titlebar no -use_cursor no

- name: Create .bash_profile
  become: yes
  become_user: openslides_projector
  copy:
    dest: ~/.bash_profile
    content: |
      sleep 5  # this should be done in systemd
      xset -dpms # disable DPMS (Energy Star) features.
      xset s off # disable screen saver
      xset s noblank # don't blank the video device
      [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

- name: Ensures /etc/systemd/system/getty@tty1.service.d/ dir exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory

- name: Autologin
  become: yes
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Unit]
      After=openslides@8404.service
      Requires=openslides@8400.service
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin openslides_projector --noclear %I $TERM
  register: createAutologinSystemFile

- name: Reload systemd units
  when: createAutologinSystemFile.changed
  command: systemctl daemon-reload
  become: yes

- name: Configure raspi boot conf
  become: yes
  lineinfile:
    dest: /boot/config.txt
    regexp: ^disable_overscan=
    line: disable_overscan=1
